#!/usr/bin/python3

from mincall.align_utils import extend_cigars_in_sam
import argparse


parser = argparse.ArgumentParser()
parser.add_argument("sam_file")
parser.add_argument("fastx_file")
parser.add_argument("ref_file")
parser.add_argument("--output", "-o", type=str, default=None, dest='sam_out')
args = parser.parse_args()

extend_cigars_in_sam(args.sam_file, args.ref_file, args.fastx_file, args.sam_out)


