version: "v0.1"
train:
  train_data:
    - name: "r9.4"
      dir: "./mincall/example"
  test_data:
    - name: "r9.4"
      dir: "./mincall/example"
  seq_length: 40
  batch_size: 10
  logdir: "./logs"
embed:
  window: 2
  stride: 10
  receptive_field: 5
  embedding_size: 10
