version: "v0.1"
train:
  train_data:
    - name: "r9.4"
      dir: "./mincall/example"
  test_data:
    - name: "r9.4"
      dir: "./mincall/example"
  model_name: "dummy"
  model_hparams:
    num_layers: 5
  surrogate_base_pair: false
  train_steps: 60
  init_learning_rate: !!float 1e-4
  lr_decay_steps: 10000
  lr_decay_rate: 0.5
  seq_length: 40
  batch_size: 10
  logdir: "./logs"
hyperparam:
  train_data:
    - name: "r9.4"
      dir: "./mincall/example"
  test_data:
    - name: "r9.4"
      dir: "./mincall/example"
  model_name: "dummy"
  model_hparams:
    num_layers:
      min: 2
      max: 5
      type: "int"
  work_dir: "logs"
  surrogate_base_pair: false
  init_learning_rate: !!float 1e-4
  train_steps: 60
  lr_decay_steps: 10000
  lr_decay_rate: 0.5
  seq_length: 40
  batch_size: 10
  solver_class: "sigopt"
embed:
  window: 2
  stride: 10
  receptive_field: 10
  embedding_size: 5
  train_steps: 10000
  batch_size: 64
